package entity;

public class Rapport{
    private String contenu="No Rapport for now !";
    private Radiologue radiologue;

    public Rapport(String contenu,Radiologue radiologue) {
        this.radiologue = radiologue;
        this.contenu = contenu;
    }
    @Override
    public String toString() {
        return this.contenu+
                "\nGenerated by : "+this.radiologue.getNom()+" "+this.radiologue.getPrenom();
    }
}

